/*
 * THIS FILE IS AUTOMATICALLY GENERATED
 *
 * Generator:     sensirion-driver-generator 0.38.1
 * Product:       stc3x
 * Model-Version: 1.0.0
 */
/*
 * Copyright (c) 2024, Sensirion AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of Sensirion AG nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
#include "sensirion_common.h"
#include "sensirion_i2c_hal.h"
#include "stc3x_i2c.h"
#include <inttypes.h>  // PRIx64
#include <stdio.h>     // printf

#define sensirion_hal_sleep_us sensirion_i2c_hal_sleep_usec

int main(void) {
    int16_t error = NO_ERROR;
    sensirion_i2c_hal_init();
    stc3x_init(STC31_C_I2C_ADDR_29);

    uint32_t product_id = 0;
    uint64_t serial_number = 0;
    sensirion_hal_sleep_us(14000);
    //
    // Output the product identifier and serial number
    //
    error = stc3x_get_product_id(&product_id, &serial_number);
    if (error != NO_ERROR) {
        printf("error executing get_product_id(): %i\n", error);
        return error;
    }
    printf("Product id = %u\n", product_id);
    printf("Serial Number = %" PRIx64 "\n", serial_number);
    //
    // Measure STC31-C CO2 in air in range 0% - 40%
    // or STC31 CO2 in air in range 0% - 25%
    //
    error = stc3x_set_binary_gas(19);
    if (error != NO_ERROR) {
        printf("error executing set_binary_gas(): %i\n", error);
        return error;
    }
    //
    // Enable weak smoothing filter for measurement.
    // This will decrease the signal noise but increase response time.
    //
    error = stc3x_enable_weak_filter();
    if (error != NO_ERROR) {
        printf("error executing enable_weak_filter(): %i\n", error);
        return error;
    }
    uint16_t co2_concentration_ticks = 0;
    uint16_t temperature_ticks = 0;
    uint16_t repetition = 0;
    for (repetition = 0; repetition < 100; repetition++) {
        //
        // Slow down the sampling to 1Hz
        //
        sensirion_hal_sleep_us(1000000);
        //
        // Set default humidity of 50%. Adjust the value to your environment or
        // use the actual humidity read out from the SHT4x sensor on the STC31-C
        // evaluation kit.
        //
        error = stc3x_set_relative_humidity_raw(32768);
        if (error != NO_ERROR) {
            printf("error executing set_relative_humidity_raw(): %i\n", error);
            continue;
        }
        error = stc3x_measure_gas_concentration_raw(&co2_concentration_ticks,
                                                    &temperature_ticks);
        if (error != NO_ERROR) {
            printf("error executing measure_gas_concentration_raw(): %i\n",
                   error);
            continue;
        }
        //
        // Print CO2 concentration in ticks and temperature ticks.
        // CO2 in VOL%: 100 * (co2_concentration_ticks - 2^14) / 2^15
        // Temperature in °C: temperature_ticks / 200.0
        //
        printf("CO2 concentration Ticks = %u\n", co2_concentration_ticks);
        printf("Temperature Ticks = %u\n", temperature_ticks);
    }

    return NO_ERROR;
}
